// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5xWw8nQ8iEa1UCuzmTinfeD9Um_YlGA4',
    appId: '1:1090058725450:android:afd2d0aeb8d9867d37deb3',
    messagingSenderId: '1090058725450',
    projectId: 'sorting-algo-project',
    storageBucket: 'sorting-algo-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkb-NAtefvkueiHf3hzKIzzjNyXZ_fPOs',
    appId: '1:1090058725450:ios:a234d7387212144e37deb3',
    messagingSenderId: '1090058725450',
    projectId: 'sorting-algo-project',
    storageBucket: 'sorting-algo-project.appspot.com',
    iosClientId: '1090058725450-kpr6c32qoqj1jcfrsh1i7q2s68vpleih.apps.googleusercontent.com',
    iosBundleId: 'com.sortingAlgo.sortingalgorithms',
  );
}
